language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head    # green, but unstable
    - rvm: jruby-head   # green, but unstable
    - rvm: rbx-18mode   # seems to be running 1.9 mode instead!?
    - rvm: rbx-19mode   # segfaulting in String#ascii_only?
